package ibotsmp3player;

import static ibotsmp3player.UI.MX;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Menu extends javax.swing.JFrame {
    
  //  UI ui= new UI();
    /**
     * Creates new form Menu
     */
    
    Playlist playlist = new Playlist();
    About abt = new About();
    static boolean singleSong = false;
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        backGroundImage = new javax.swing.JLabel();
        backGroundLayer = new javax.swing.JLayeredPane();
        openBtn = new javax.swing.JLabel();
        opnTxt = new javax.swing.JLabel();
        abtBtn = new javax.swing.JLabel();
        abtTxt = new javax.swing.JLabel();
        addPlaylistBtn = new javax.swing.JLabel();
        addPlaylistTxt = new javax.swing.JLabel();

        setTitle("Menu");
        setLocation(new java.awt.Point(1075, 200));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MenuBG.png"))); // NOI18N

        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/open.png"))); // NOI18N
        openBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openBtnMouseExited(evt);
            }
        });

        opnTxt.setBackground(new java.awt.Color(153, 153, 153));
        opnTxt.setForeground(new java.awt.Color(255, 255, 255));
        opnTxt.setText("Open");
        opnTxt.setOpaque(true);
        opnTxt.setVisible(false);

        abtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/about.png"))); // NOI18N
        abtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abtBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abtBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abtBtnMouseExited(evt);
            }
        });

        abtTxt.setBackground(new java.awt.Color(153, 153, 153));
        abtTxt.setForeground(new java.awt.Color(255, 255, 255));
        abtTxt.setText("About Us");
        abtTxt.setOpaque(true);
        abtTxt.setVisible(false);

        addPlaylistBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/addplaylist.png"))); // NOI18N
        addPlaylistBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPlaylistBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPlaylistBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPlaylistBtnMouseExited(evt);
            }
        });

        addPlaylistTxt.setBackground(new java.awt.Color(153, 153, 153));
        addPlaylistTxt.setForeground(new java.awt.Color(255, 255, 255));
        addPlaylistTxt.setText("Playlist");
        addPlaylistTxt.setOpaque(true);
        addPlaylistTxt.setVisible(false);

        backGroundLayer.setLayer(openBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backGroundLayer.setLayer(opnTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backGroundLayer.setLayer(abtBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backGroundLayer.setLayer(abtTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backGroundLayer.setLayer(addPlaylistBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backGroundLayer.setLayer(addPlaylistTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout backGroundLayerLayout = new javax.swing.GroupLayout(backGroundLayer);
        backGroundLayer.setLayout(backGroundLayerLayout);
        backGroundLayerLayout.setHorizontalGroup(
            backGroundLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayerLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(backGroundLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(abtBtn)
                    .addComponent(openBtn)
                    .addComponent(addPlaylistBtn))
                .addGap(18, 18, 18)
                .addGroup(backGroundLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opnTxt)
                    .addComponent(addPlaylistTxt)
                    .addComponent(abtTxt))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        backGroundLayerLayout.setVerticalGroup(
            backGroundLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayerLayout.createSequentialGroup()
                .addGroup(backGroundLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backGroundLayerLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(opnTxt)))
                .addGroup(backGroundLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayerLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(addPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backGroundLayerLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(addPlaylistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backGroundLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayerLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(abtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abtTxt)
                        .addGap(63, 63, 63))))
        );

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundLayer)
            .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backGroundLayout.createSequentialGroup()
                    .addComponent(backGroundImage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addComponent(backGroundLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backGroundLayout.createSequentialGroup()
                    .addComponent(backGroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPlaylistBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPlaylistBtnMouseExited
        // TODO add your handling code here:
        addPlaylistTxt.setVisible(false);
        addPlaylistBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/addplaylist.png")));
    }//GEN-LAST:event_addPlaylistBtnMouseExited

    private void addPlaylistBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPlaylistBtnMouseEntered
        // TODO add your handling code here:
        addPlaylistTxt.setVisible(true);
        addPlaylistBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/addplaylistHLT.png")));
    }//GEN-LAST:event_addPlaylistBtnMouseEntered

    private void addPlaylistBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPlaylistBtnMouseClicked
        // TODO add your handling code here:
        playlist.setVisible(true);
    }//GEN-LAST:event_addPlaylistBtnMouseClicked

    private void abtBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abtBtnMouseExited
        // TODO add your handling code here:
        abtTxt.setVisible(false);
        abtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/about.png")));
    }//GEN-LAST:event_abtBtnMouseExited

    private void abtBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abtBtnMouseEntered
        // TODO add your handling code here:
        abtTxt.setVisible(true);
        abtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aboutHLT.png")));
    }//GEN-LAST:event_abtBtnMouseEntered

    private void abtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abtBtnMouseClicked
        // TODO add your handling code here:
        abt.setVisible(true);
    }//GEN-LAST:event_abtBtnMouseClicked

    private void openBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseExited
        // TODO add your handling code here:
        opnTxt.setVisible(false);
        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Open.png")));
    }//GEN-LAST:event_openBtnMouseExited

    private void openBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseEntered
        // TODO add your handling code here:
        opnTxt.setVisible(true);
        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/OpenHLT.png")));
    }//GEN-LAST:event_openBtnMouseEntered

    private void openBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseClicked

        FileFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3", "mpeg3");

        JFileChooser fileChooser = new JFileChooser("F:\\IBotsMp3Player\\src\\Music");
        fileChooser.addChoosableFileFilter(filter);

        int returnVal = fileChooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String song = selectedFile + "";

            String name = fileChooser.getSelectedFile().getName();
            singleSong = true;
            UI.display.setText("      Now Playing....");
            UI.songTitle.setText("" + name);
            MX.Stop();
            MX.playMusic(song);

            UI.playpauseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pause.png")));
            UI.songplay = true;
            UI.songavailable = true;

        }

    }//GEN-LAST:event_openBtnMouseClicked
    public void menudispose()
    {
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abtBtn;
    private javax.swing.JLabel abtTxt;
    private javax.swing.JLabel addPlaylistBtn;
    private javax.swing.JLabel addPlaylistTxt;
    private javax.swing.JPanel backGround;
    private javax.swing.JLabel backGroundImage;
    private javax.swing.JLayeredPane backGroundLayer;
    private javax.swing.JLabel openBtn;
    private javax.swing.JLabel opnTxt;
    // End of variables declaration//GEN-END:variables
}
